[package]
links = "foo"
name = "rust_sample"
build = "build.rs"
version = "0.1.0"
authors = ["mithril1992 <nomber00@gmail.com>"]

[lib]
crate-type = ["rlib", "staticlib"]

[dependencies]
libc = "0.2"
getopts = "0.2"

[build-dependencies]
gcc = "0.3"